#!/bin/bash
# 濟州島景點圖片下載腳本
# 請手動從以下網址下載圖片並重命名

echo "=== 濟州島行程景點圖片下載指南 ==="
echo ""
echo "請訪問以下 Google Maps 連結，右鍵儲存圖片到 images/ 資料夾："
echo ""
echo "Day 1 景點:"
echo "1. 東門市場 (dongmun_market.jpg)"
echo "   https://www.google.com/maps/search/?api=1&query=Dongmun+Traditional+Market+Jeju"
echo ""
echo "2. 9.81 Park (981park.jpg)"
echo "   https://www.google.com/maps/search/?api=1&query=9.81+Park+Jeju"
echo "   或官網: https://www.981park.com/"
echo ""
echo "Day 2 景點:"
echo "3. 倫敦貝果博物館 (london_bagel.jpg)"
echo "   https://www.google.com/maps/search/?api=1&query=London+Bagel+Museum+Jeju"
echo ""
echo "4. 山君不離 (sangumburi.jpg)"
echo "   https://www.google.com/maps/search/?api=1&query=Sangumburi+Crater"
echo ""
echo "5. 城山日出峰 (seongsan.jpg)"
echo "   https://www.google.com/maps/search/?api=1&query=Seongsan+Ilchulbong"
echo ""
echo "Day 4 景點:"
echo "6. 雪綠茶博物館 (osulloc.jpg)"
echo "   https://www.google.com/maps/search/?api=1&query=Osulloc+Tea+Museum"
echo ""
echo "7. 正房瀑布 (jeongbang_falls.jpg)"
echo "   https://www.google.com/maps/search/?api=1&query=Jeongbang+Waterfall"
echo ""
echo "下載完成後，將圖片放入 images/ 資料夾即可"

